#optional: if commented out all is taken care of by the default settings
# NB. global options apply to all run_ids 

#global_plotting_options:
#  regions: ["europe", "global"] # Have regions here, if you want for them to apply to all streams (map generation)
#  image_format : "png" #options: "png", "pdf", "svg", "eps", "jpg" ..
#  animation_format: "gif" #options: "mp4", "gif"
#  log_colorbar: true

#  dpi_val : 300
#  fps: 2
#  n_bins: 50 #number of bins for histograms. 
#  log_x: true #use log scale for x axis in histograms. 
#  log_y: true #use log scale for y axis in histograms. 
#  ERA5:
#    use_datashader: false
#    marker_size: 2
#    scale_marker_size: 1
#    marker: "o"
#    add_healpix_grid: false
#    healpix_nside: 4
#    # alpha: 0.5
#    2t: 
#      vmin: 250
#      vmax: 300
#    10u:
#      vmin: -40
#      vmax: 40


# max_workers: 36  # hard cap on parallel workers (I/O, plotting, scoring)

evaluation:
  metrics  : ["rmse", "froct"]
  regions: ["global", "ICON"]
  summary_plots : true
  ratio_plots : false
  heat_maps : false
  summary_dir: "./plots/"
  plot_ensemble: "members" #supported: false, "std", "minmax", "members"
  plot_score_maps: false #plot scores on a 2D maps. it slows down score computation
  plot_score_animations: false #plot animations of score maps across forecast steps. it slows down score computation
  print_summary: false #print out score values on screen. it can be verbose
  log_scale: false
  add_grid: false
  score_cards: false
  bar_plots: false
  num_processes: 0  #options: int, "auto", 0 means no parallelism (default)
  # baseline: "ar40mckx"


global_plotting_options:
  regions: ["ICON", "global"]
  ICON:
    use_datashader: true
  ERA5:
    use_datashader: true



default_streams:
  ERA5:
    channels: ["2t", "q_850", "10v", "10u", "z_500", "t_850", "u_850", "v_850"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: [0]
      forecast_step: 1-20 #supported: "all", [1,2,3,...], "1-50" (equivalent of [1,2,3,...50])
      ensemble: "all" #supported: "all", "mean", [0,1,2]
      plot_maps: true
      plot_target: true
      plot_histograms: false
      plot_animations: true
  ICON:
    channels: ["T_2M", "QV_850", "U_10M", "V_10M", "FI_500", "T_850", "U_850", "V_850"]
    evaluation:
      forecast_step: "all"
      sample: "all"
      ensemble: "all" #supported: "all", "mean", [0,1,2]
    plotting:
      sample: [0]
      forecast_step: 1-20
      ensemble: "all" #supported: "all", "mean", [0,1,2]
      plot_maps: true
      plot_target: true
      plot_histograms: false
      plot_animations: true
      plot_subtimesteps: true

run_ids :
  za6hqboe:
    label: "ICON + ERA5 (64 epochs)"
    results_base_dir: "./results/za6hqboe"

  mfmyuhjb:
    label: "ICON + ERA5 (128 epochs)"
    results_base_dir: "./results/mfmyuhjb"

  # scn09avu:
  #   label: "ICON + ERA5 (healpix=5)"
  #   results_base_dir : "./results/scn09avu"
  #   #NEW: if "streams" is not specified, the default streams are used
    
  # vxwhnemg:
  #   label: "ICON + ERA5 (healpix=6)"
  #   results_base_dir : "./results/vxwhnemg"
  #   #NEW: if "streams" is not specified, the default streams are used

  # a6ukne1p:
  #   label: "ICON"
  #   results_base_dir : "./results/a6ukne1p"
  #   #NEW: if "streams" is not specified, the default streams are used
