parallelize: false
stages:
  - name: cerraCellRetry
    stage: train
    run_id: caea0006
    config_files:
      - config/cerra_autoencoding.yml
      - config/cerra_ae_cellqueries.yml
    nodes: 1
    chain_jobs: 1
    cleanup_scripts: false
    slurm_args:
      - --ntasks=1
      - --ntasks-per-node=1
      - --cpus-per-task=8
      - --gres=gpu:1
      - --mem=64G
      - --exclusive=user
      - --partition=debug
      - --time=00:25:00
      - --uenv-passthrough=ignore
