stages:
  - name: pretrain
    stage: train
    config_files:
      - config/config_forecasting.yml
    options:
      - ae_local_max_tokens_per_cell=256
      - data_loading.num_workers=6
    chain_jobs: 4
    nodes: 2
    slurm_args:
      - "--time=23:59:00"

