parallelize: false
stages:
  - name: cerraGlobalEval
    stage: inference
    run_id: caei0018
    from_run_id: caea0018
    mini_epoch: 10
    nodes: 1
    cleanup_scripts: false
    slurm_args:
      - --ntasks=1
      - --ntasks-per-node=1
      - --cpus-per-task=8
      - --gres=gpu:1
      - --mem=64G
      - --exclusive=user
      - --partition=debug
      - --time=00:10:00
      - --uenv-passthrough=ignore
