stages:
  - name: pretrain
    stage: train
    config_files:
      - config/config_forecasting.yml
    options:
      - training_config.num_mini_epochs=16
      - data_loading.num_workers=4
      - ae_local_max_tokens_per_cell=256
    chain_jobs: 2
    nodes: 8
    slurm_args:
      - "--time=23:59:00"
